---
title: "Scaling Color"
author: "Isaac Neuhaus"
date: "06/04/2024"
output:
  html_document:
    toc: yes
    theme: cerulean
    smart: no
    self_contained: yes
editor_options: 
  chunk_output_type: console
---

# Load Libraries
```{r setup}
if (!("ggplot2" %in% installed.packages())) {
    install.packages('ggplot2')
}
library('ggplot2')
if (!("devtools" %in% installed.packages())) {
    install.packages('devtools')
}
if (!("canvasXpress" %in% installed.packages())) {
    devtools::install_github('neuhausi/canvasXpress')
}
#devtools::install_local("~/git/canvas/R/canvasXpress.tar.gz", build_manual = TRUE, upgrade = "always")
library('canvasXpress')
```


## Load Data
```{r}
ToothGrowth$dose <- as.factor(ToothGrowth$dose)
mtcars$cyl <- as.factor(mtcars$cyl)
```

## No Scale
```{r}
s <- ggplot(mtcars, aes(x=wt, y=mpg, color=cyl)) + geom_point()
s
canvasXpress(s)
```

## scale_color_hue
```{r}
s1 = s + scale_color_hue(l=40, c=35)
s1
canvasXpress(s1)
```

## scale_color_manual
```{r}
s1 = s + scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9"))
s1
canvasXpress(s1)
```

## scale_color_manual with breaks
```{r}
s1 = s + scale_color_manual(breaks = c("8", "6", "4"), values = c("red", "blue", "green"))
s1
canvasXpress(s1)
```

##  scale_color_brewer
```{r}
s1 = s + scale_color_brewer(palette="Dark2")
s1
canvasXpress(s1)
```

## scale_color_grey
```{r}
s1 = s + scale_color_grey(start=0.8, end=0.2) + theme_classic()
s1
canvasXpress(s1)
```

## scale_color_gradient
```{r}
s2 <- ggplot(mtcars, aes(x=wt, y=mpg, color=qsec)) + geom_point()
s1 = s2 + scale_color_gradient(low="blue", high="red")
s1
canvasXpress(s1)
```

## scale_color_gradient2
```{r}
mid<-mean(mtcars$qsec)
s1 = s2 + scale_color_gradient2(midpoint=mid, low="blue", mid="white", high="red", space="Lab" )
s1
canvasXpress(s1)
```

## scale_colour_steps
```{r}
set.seed(1)
df <- data.frame(
  x = runif(100),
  y = runif(100),
  z1 = rnorm(100)
)

s1 <- ggplot(df, aes(x, y)) + geom_point(aes(colour = z1)) + scale_colour_steps()
s1
canvasXpress(s1)
```

## scale_colour_stepsn
```{r}
set.seed(1)
df <- data.frame(
  x = runif(100),
  y = runif(100),
  z1 = rnorm(100)
)

s1 <- ggplot(df, aes(x, y)) + geom_point(aes(colour = z1)) + scale_colour_stepsn(colours = terrain.colors(10))
s1
canvasXpress(s1)
```